# Generated by Django 5.2.7 on 2025-10-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCategory', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=500, unique=True)),
                ('course_initial', models.CharField(max_length=10, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('faculty_name', models.CharField(blank=True, max_length=300)),
                ('faculty_initial', models.CharField(max_length=50, unique=True)),
                ('section', models.PositiveIntegerField()),
            ],
        ),
    ]
