# Generated by Django 5.2.7 on 2025-10-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='course_initial',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='course_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='faculty_initial',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='slug',
            field=models.SlugField(),
        ),
    ]
