# Generated by Django 5.2.7 on 2025-10-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_coursecategory_course_initial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategory',
            name='course_initial',
        ),
        migrations.RemoveField(
            model_name='coursecategory',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='coursecategory',
            name='faculty_initial',
        ),
        migrations.RemoveField(
            model_name='coursecategory',
            name='faculty_name',
        ),
        migrations.RemoveField(
            model_name='coursecategory',
            name='section',
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='dep_name',
            field=models.CharField(default='Computer Science', max_length=500),
        ),
    ]
