# Generated by Django 5.2.7 on 2025-10-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_coursecategory_course_initial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='slug',
            field=models.SlugField(max_length=500),
        ),
    ]
