# Generated by Django 5.2.7 on 2025-11-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_coursecategory_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='courseCategory',
            field=models.CharField(default='CSE', max_length=200),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='dep_name',
            field=models.CharField(max_length=500),
        ),
    ]
