# Generated by Django 5.2.7 on 2025-10-26 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_remove_coursecategory_course_initial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=500)),
                ('course_initial', models.CharField(max_length=10)),
                ('slug', models.SlugField()),
                ('faculty_name', models.CharField(blank=True, max_length=300)),
                ('faculty_initial', models.CharField(max_length=50)),
                ('section', models.PositiveIntegerField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.coursecategory')),
            ],
        ),
    ]
