# Generated by Django 5.2.7 on 2025-11-15 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_section_alter_course_slug_sectionnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionnote',
            name='section',
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sectionnote',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='courses.course'),
        ),
    ]
