# Generated by Django 5.2.7 on 2025-12-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lecturefinalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='class_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturefinalnote',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecturefinalnote',
            name='next_pdf_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturefinalnote',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='final_pdfs/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='lecturefinalnote',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
