# Generated by Django 5.2.7 on 2025-12-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_class_days_course_class_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_initial', 'course_name', 'section')},
        ),
    ]
